### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by hello-world-noob** [samuelstjean/spams-python#14]
Hello,

I have installed your module with pip install spams-bin, but when I try to import spams I have the following error:

Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import spams
  File "C:\Documents\venv\lib\site-packages\spams\__init__.py", line 2, in <module>
    from .spams import *
  File "C:\Documents\venv\lib\site-packages\spams\spams.py", line 6, in <module>
    import spams_wrap
  File "C:\Documents\venv\lib\site-packages\spams_wrap\__init__.py", line 2, in <module>
    from .spams_wrap import *
  File "C:\Documents\venv\lib\site-packages\spams_wrap\spams_wrap.py", line 19, in <module>
    from ._spams_wrap import *
ImportError: DLL load failed: The specified module could not be found.

I understand that spams_wrap is having trouble importing the C++ code, but I don't understand why... Have I missed something? (Sorry I am a noob...).

I have a Windows machine and I am using Python 3.6...

Can you help me please?

**Comment by samuelstjean** [comment]
If there is no more info, I'd think it might be that you are missing some dll that the file is calling. For example, easy stuff would be the C++ redistributable from windows, but that should be already installed since bout everything needs it.

The other thing is that it calls the mkl version for linalg stuff, which are not included in the package since there wasn't any easy way to do it automatically on windows. So you'll probably need the numpy version of the libs built with intel mkl, and not the generic and official openblas one. If you installed numpy through conda it should fetch the mkl version normally. I alos hope it does not need the exact same version that I built it with, because then nobody would be able to use that package ever in that case.

**Comment by hello-world-noob** [comment]
Indeed the problem was with my pip install of numpy... I used conda install instead and now it works ! 
Thank you very much for your help !
