### ISSUE TITLE
ImportError: DLL load failed while importing _spams_wrap

### ISSUE THREAD

**Issue by Guym142** [samuelstjean/spams-python#16]
Hi,
I'm trying to use spams on windows.
I've installed Intel oneAPI (mkl) and using Anaconda3.
I've installed the package but I get the following error on 'import spams':

`>>> import spams

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\guymo\anaconda3\lib\site-packages\spams\__init__.py", line 2, in <module>
    from .spams import *
  File "C:\Users\guymo\anaconda3\lib\site-packages\spams\spams.py", line 6, in <module>
    import spams_wrap
  File "C:\Users\guymo\anaconda3\lib\site-packages\spams_wrap\__init__.py", line 2, in <module>
    from .spams_wrap import *
  File "C:\Users\guymo\anaconda3\lib\site-packages\spams_wrap\spams_wrap.py", line 19, in <module>
    from ._spams_wrap import *
ImportError: DLL load failed while importing _spams_wrap: The specified module could not be found.`

I tried reinstalling Anaconda and mkl but it doesn't seem to work.
Thank you

**Comment by samuelstjean** [comment]
Normally it should try fetching the version that numpy is using, but in the meantime they changed the name of the dll, I think that's why it is not working right now unfortunately. I'm still working a bit on it to see if I can make it work though.

**Comment by samuelstjean** [comment]
I gave a try for the py 3.7 version of windows in this build https://github.com/samuelstjean/spams-python/suites/3630670560/artifacts/87875714, normally the other ones should work also since they all mimic the same thing. I'm not sure if it may conflict with other installed stuff since the file names are preserved, and the builds were throwing weird errors because of that, so it may need additional tweaking on my part due to that. It may also include too much files for the same reason.

**Comment by andreped** [comment]
Did you make any progress? I am observing the same issue using Python 3.6.

**Comment by Guym142** [comment]
> Did you make any progress? I am observing the same issue using Python 3.6.

Couldn't make it work on windows, I moved to Ubuntu to develop with spams

**Comment by samuelstjean** [comment]
Based on 'if it compiles, it works', here is a version with openblas, hopefully it's also speedy https://github.com/samuelstjean/spams-python/suites/3713850640/artifacts/90771822

**Comment by samuelstjean** [comment]
It's freshly out now https://github.com/samuelstjean/spams-python/releases/tag/v2.6.4

**Comment by andreped** [comment]
@samuelstjean I observed that you only built binaries for Python >=3.7. Is there a reason v3.6 was dropped? This version is still quite heavily used.

**Comment by samuelstjean** [comment]
Sheer laziness because it will be eol in three months. I can just add it back, I think it had some build issues in an old version, but I can give it a try now.

**Comment by samuelstjean** [comment]
Just added it now here and on pipy

**Comment by andreped** [comment]
@samuelstjean: Importing SPAMS in Python `import spams` no longer prompts any errors, so I think it has been fixed. Thanks! :)

**tested using Python 3.6

**Comment by samuelstjean** [comment]
So normally the online version should be working (and hopefully fast on modern processors). If anything else seems to be missing feel free to ask. I'm worried for example that performance on fancy intel processor might have tanked since now everything is tied to openblas in the premade versions. Well, it was for me back in 2015 at least, so hopefully they fixed it in the meantime.
